server:
  port: 9600

vertx:
  security:
    enabled: true
    jwt:
      enabled: true
      mapping-urls:
      secret-original: 5930d1e5-0b3a-4efb-bbfb-8e039fbe8b38
      secret-gen-algorithm: sha1-hex
      secret-key: ebb45472b2b2f2332a878adf21ac8afdc65474e2
      header: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      expired-in: 15552000000 #6 th√°ng

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Apply to all paths
            allowedOrigins: "*" # Allow all origins
            allowedMethods: [ "GET", "POST", "PUT", "DELETE", "OPTIONS" ]
            allowedHeaders: [ "*" ] # Allow all headers
            allowCredentials: false # Set to false when using "*"