server:
  port: 9500

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/authenticator/**

        - id: system-service
          uri: http://localhost:9600
          predicates:
            - Path=/system/**

        - id: admin-service
          uri: http://localhost:9100
          predicates:
            - Path=/adminapi/**

        - id: application-service
          uri: http://localhost:9200
          predicates:
            - Path=/application/**

        - id: integration-service
          uri: http://localhost:9300
          predicates:
            - Path=/integration/**

        - id: notification-service
          uri: http://localhost:9400
          predicates:
            - Path=/notification/**

        - id: portal-service
          uri: https://localhost:9400
          predicates:
            - Path=/portal/**